CREATE FUNCTION FN_THONGTINPHONGDEAN 
(@MAPHG INT)
 RETURNS @LIST TABLE (TENPHONG NVARCHAR(15),TENTRUONGPHONG NVARCHAR(30), SOLUONGDEAN INT)
AS
BEGIN
INSERT INTO @LIST
 SELECT A.TENPHG, B.HONV +' '+ B.TENLOT +' '+B.TENNV,
 (SELECT COUNT(C.MADA) FROM DEAN C WHERE C.PHONG = A.MAPHG)
 FROM PHONGBAN A INNER JOIN NHANVIEN B ON A.MAPHG =B.PHG
 RETURN;
 END;

 SELECT * FROM [dbo].[FN_THONGTINPHONGDEAN](1);
