create FUNCTION FN_TUOI(@MANV NVARCHAR (9))
RETURNS INT
AS
BEGIN
 RETURN(
  SELECT DATEDIFF(YEAR,NGSINH,GETDATE()) +1 FROM NHANVIEN WHERE MANV = @MANV
 );
 END;


 SELECT [dbo].[FN_TUOI](006);